### ISSUE TITLE
Cadu: Tensorflow (basic setup)

### ISSUE THREAD

**Issue by fititnt** [EticaAI/eticaai-infrastructure#14]

**Comment by fititnt** [comment]
`docker run -it -p 8888:8888 tensorflow/tensorflow` on https://github.com/fititnt/tensorflow-docker-compose-test

----





![captura de tela de 2017-09-16 22-23-11](https://user-images.githubusercontent.com/812299/30517191-e3517210-9b2d-11e7-9568-e71ee4fc06fc.png)

![captura de tela de 2017-09-16 22-24-11](https://user-images.githubusercontent.com/812299/30517187-e32d4f3e-9b2d-11e7-96d7-b8188e53b19a.png)

![captura de tela de 2017-09-16 22-23-55](https://user-images.githubusercontent.com/812299/30517188-e32e2648-9b2d-11e7-86da-4bd0fd8e8da2.png)

![captura de tela de 2017-09-16 22-23-45](https://user-images.githubusercontent.com/812299/30517189-e32e7e04-9b2d-11e7-8b2e-dd23698617ff.png)

![captura de tela de 2017-09-16 22-23-31](https://user-images.githubusercontent.com/812299/30517190-e3347b88-9b2d-11e7-9efb-dcf603f6c847.png)

**Comment by fititnt** [comment]
docker-compose.yml:

```
version: '3'
services:
  tensorflow:
    image: tensorflow/tensorflow:latest
    container_name: tensorflow
    expose:
      - 8888
    ports:
      - 8888:8888
```

from https://github.com/fititnt/tensorflow-docker-compose-test/commit/6e98fddc441f0d445cd34341d494dcbfab6cf50f.

At this point is more about define how people will access tensorflow. We could configure later something much more robust.

Not sure if this issue should be closed and another one created in future.
